name: Android Build and Test

on:
  push:
    branches: [ "feature/unit-test", "main", "release/*", "feature/ZEUS-4174-unit-tests-fix"]
  pull_request:
    branches: [ "feature/unit-test", "main", "release/*" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Android SDK
        uses: reactivecircus/setup-android@v2
        with:
          components: 'platform-tools,android-31,build-tools-31.0.0'
          licenses: 'android-sdk-license-.+'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build and run unit tests
        run: ./gradlew test