name: Android Build and Test

on:
  push:
    branches: [ "feature/unit-test", "main", "release/*", "feature/ZEUS-4174-unit-tests-fix"]
  pull_request:
    branches: [ "feature/unit-test", "main", "release/*" ]

jobs:
  build:
    name: Gradle build and test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: 'jdk'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean build directory
        run: ./gradlew clean

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --warning-mode=all --scan
