name: Android Build and Test

on:
  push:
    branches: [ "feature/unit-test", "main", "release/*", "feature/ZEUS-4174-unit-tests-fix"]
  pull_request:
    branches: [ "feature/unit-test", "main", "release/*" ]

jobs:

  Gradle-Build:
    name: Gradle build -> Check-out the repository and testing
    runs-on: macos-latest

    steps:
      - name: Check-out the repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: Downloading and setting up a Java 17, zulu distribution
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --warning-mode=all