name: Android Build and Test

on:
  push:
    branches: [ "feature/unit-test", "main", "release/*", "feature/ZEUS-4174-unit-tests-fix"]
  pull_request:
    branches: [ "feature/unit-test", "main", "release/*" ]

jobs:

  Gradle-Build:
    name: Gradle build and test
    runs-on: macos-latest

    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3

      - name: Downloading and setting up Java 17 (Zulu distribution)
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Android SDK components
        uses: actions/cache@v2
        with:
          path: ~/.android
          key: ${{ runner.os }}-android-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-android-

      - name: Run Unit Tests
        run: |
          ./gradlew testDebugUnitTest --warning-mode=all --stacktrace
          if [ $? -ne 0 ]; then
            echo "Unit tests failed"
            exit 1
          fi
